
version: '3'


services:
    eureka-client-2:    
        build: 
            context: ./eureka-client-2
            dockerfile: Dockerfile
        container_name: eureka-client-2    
        depends_on:
          - eureka-server
        links:
          - eureka-server
          
    eureka-client-1:
        build:
            context: ./eureka-client-1
            dockerfile: Dockerfile
        container_name: eureka-client-1
        depends_on:
          - eureka-server
        links:
          - eureka-server

    eureka-server:    
        build: 
            context: ./eureka-server
            dockerfile: Dockerfile
        container_name: eureka-server
        ports:
          - 8761:8761 # Forward the exposed port 8761 on the container to port 8761 on the host machine

 